config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root :controller => 'my_threads', :action => 'index'

  resources :my_threads, shallow: true do
    resources :my_comments, :except => [:index, :show]
  end

end

app/models/my_comment.rb
class MyComment < ActiveRecord::Base
  belongs_to :my_thread
end

app/models/my_thread.rb
class MyThread < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/my_comments_controller.rb
class MyCommentsController < ApplicationController
  before_action :set_my_comment, only: [:show, :edit, :update, :destroy]

  def new
    @my_comment = MyComment.new
    @my_thread_id = params[:my_thread_id]
  end

  def edit
    @my_thread_id = @my_comment.my_thread_id
  end

  def create
    @my_comment = MyComment.new(my_comment_params)
    @my_thread_id = @my_comment.my_thread_id
    #上記にいずれuser_idを渡す
    if @my_comment.save
      redirect_to controller: 'my_threads', action: 'show', id: @my_thread_id
      return
    end
    render :new, location: @my_comment
  end

  def update
    @my_thread_id = @my_comment.my_thread_id
    if @my_comment.update(my_comment_params)
      redirect_to controller: 'my_threads', action: 'show', id: @my_thread_id
      return
    end
    render :edit, location: @my_comment
  end

  def destroy
    @my_thread_id = @my_comment.my_thread_id
    if @my_comment.destroy
      redirect_to controller: 'my_threads', action: 'show', id: @my_thread_id
      return
    end
    #flash で一時的なメッセージを作成したほうがよい
    redirect_to controller: 'my_threads', action: 'show', id: @my_thread_id
  end

  private

    def set_my_comment
      return unless params[:id]
      @my_comment = MyComment.find(params[:id])
    end

    def my_comment_params
      params.require(:my_comment).permit(:overview, :my_thread_id)
    end

end

app/controllers/my_threads_controller.rb
class MyThreadsController < ApplicationController
  before_action :set_my_thread, only: [:show, :edit, :update, :destroy]

  def index
    @my_threads = MyThread.all
  end

  def show
    @my_comments = MyComment.where(my_thread_id: params['id'])
  end

  def new
    @my_thread = MyThread.new
  end

  def edit
  end

  def create
    @my_thread = MyThread.new(my_thread_params)
    if @my_thread.save
      render :show, location: @my_thread
      return
    end
    render :new, location: @my_thread
  end

  def update
    if @my_thread.update(my_thread_params)
      redirect_to my_thread_path(@my_thread)
#      render :show, location: @my_thread
      return
    end
    render :edit, location: @my_thread
  end

  def destroy
    if @my_thread.destroy
      redirect_to my_threads_path
      return
    end
    render :edit, location: @my_thread
  end

  private

    def set_my_thread
      return unless params[:id]
      @my_thread = MyThread.find(params[:id])
    end

    def my_thread_params
      params.require(:my_thread).permit(:title, :overview)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_threads/my_comments_helper.rb
module MyThreads::MyCommentsHelper
end

app/helpers/my_threads_helper.rb
module MyThreadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bbs0base</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Sign out', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } %>

<%= yield %>

</body>
</html>

app/views/my_comments/_form.html.erb
<%= form_for(@my_comment, :url => {:action => 'create'}) do |f| %>
  <div class="field">
    <%= f.label :overview %><br>
    <%= f.text_field :overview %>
  </div>
    <%= f.hidden_field :my_thread_id, :value => @my_thread_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_comments/edit.html.erb
<h1>Editing My Comment</h1>
<%= form_for(@my_comment, :url => {:action => 'update'}) do |f| %>
  <div class="field">
    <%= f.label :overview %><br>
    <%= f.text_field :overview %>
  </div>
    <%= f.hidden_field :my_thread_id, :value => @my_thread_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @my_comment %> |
<%= link_to 'Back', my_thread_path(@my_thread_id) %>

app/views/my_comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', my_thread_path(@my_thread_id) %>

app/views/my_threads/_form.html.erb
<%= form_for(@my_thread) do |f| %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :overview %><br>
    <%= f.text_field :overview %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_threads/edit.html.erb
<h1>Editing my_thread</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_thread %> |
<%= link_to 'Back', my_threads_path %>

app/views/my_threads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing MyThreads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Overview</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_threads.each do |my_thread| %>
      <tr>
        <td><%= my_thread.title %></td>
        <td><%= my_thread.overview %></td>
        <td><%= link_to 'Show', my_thread %></td>
        <td><%= link_to 'Edit', edit_my_thread_path(my_thread) %></td>
        <td><%= link_to 'Destroy', my_thread, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New thread', new_my_thread_path %>

app/views/my_threads/my_comments/_form.html.erb
<%= form_for(@my_comment, :url => {:action => 'create'}) do |f| %>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :overview %><br>
    <%= f.text_field :overview %>
  </div>
    <%= f.hidden_field :my_thread_id, :value => @my_thread_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_threads/new.html.erb
<h1>New Thread</h1>

<%= render 'form' %>

<%= link_to 'Back', my_threads_path %>

app/views/my_threads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @my_thread.title %>
</p>

<p>
  <strong>Overview:</strong>
  <%= @my_thread.overview %>
</p>

<%= link_to 'Edit', edit_my_thread_path(@my_thread) %> |
<%= link_to 'Back', my_threads_path %>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Overview</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_comments.each do |comment| %>
      <tr>
        <td>User</td>
        <td><%= comment.overview %></td>
        <td><%= link_to 'Edit', edit_my_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My Comment', new_my_thread_my_comment_path(@my_thread) %>